### ISSUE TITLE
Census API - need backlog of tasks as issues

### ISSUE THREAD

**Issue by LMorgan-veraly** [hackoregon/neighborhoods-2018#14]
- __What is status, can we get a list of Issues to work so that workload can be shared?__
- __Can we get census API up with eviction lab & IMS data?__
- Previous notes - 
  - What input in and what output out?
  - What needs to be pulled from census?
  - What do other teams need from census?
    - need more definition from nbrhd team, other teams, design group
  - v1 complete by lat/lon, but some roadblocks, investigating solutions?

**Comment by hassanshamim** [comment]
closed for inactivity
