### ISSUE TITLE
Geocoding Addresses

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/neighborhoods-2018#2]

**Comment by znmeb** [comment]
I've got this coded - how do you want to deploy it? Do you want to geocode a batch of addresses up front and serve the results or do you want to geocode live in the front end / API?

**Comment by mckinneybock** [comment]
Hi! Thanks for commenting. I was testing issue notes with Lynn, and so I'm not the only one looking for a solution to this. It would be good to have a discussion at our Thursday meeting about how to proceed.

**Comment by znmeb** [comment]
I can't come to the meeting but you can hit me up in Slack most of the day.

**Comment by mckinneybock** [comment]
Thanks!
