### ISSUE TITLE
ims_nbrhd_demographics

### ISSUE THREAD

**Issue by AraOshin** [hackoregon/neighborhoods-2018#43]
As with neighborhood_ages_over_time issue, sandbox will need the values for each date to be on separate rows. In this case, two rows for each neighborhood, with a year column indicating 2000 or 2010 and then the rest of the fields for that year. So total_population_2000 and total_population_2010 would be one new column total_population. 

This could be accomplished with a materialized view but seems like this might be an okay case for just updating the tables (or more likely creating a new one from a query and then deleting the old one?) 

Also, this dataset needs to be joined with the rlisneighborhoods dataset by name. Again, this could be done with a materialized view but I think it makes sense to just create a geom column and update it with the data from the join query.

**Comment by LMorgan-veraly** [comment]
@hassanshamim see slack links for 2010 and 2000 csvs, let me know if you needed soemthing tweeked.

**Comment by hassanshamim** [comment]
This is done.  I opted for for the materialized view approach, as we have a few neighborhoods that aren't in the rlis dataset.  They aren't currently included.  If you would like ims data even if there isn't a geometry attached let me know and I'll change it to an outer join.  New materialized view is under `ims_neighborhood_demographics`.  Original data (with year as column now) is in the `ims_demographics` table.
