### ISSUE TITLE
Database changes for sandbox 

### ISSUE THREAD

**Issue by AraOshin** [hackoregon/neighborhoods-2018#54]
Here is a list of the datasets that I know I still need adjustments to in order to move forward with neighborhoods sandbox packages. I have put them in what I would prefer to be the order if possible. 

evictons_blockgroup
1. Add geom (census 2010 join on tips to geoid) 

ims_nbrhd_demographics
See : https://github.com/hackoregon/neighborhoods-2018/issues/43
1. Add geom (riles neighborhoods join) 
2. Move 2000, 2010 columns to rows.

camp_reports aggregation by neighborhood by month-year (please add column for month year in this format: Jan2018, Feb2017 etc) 

voters age groups 
https://github.com/hackoregon/neighborhoods-2018/issues/42

bike_daily_estimates/bike counts would need geom column (join on bike count locations?) 

Tax lot view by year aggregated to neighborhoods. I can write this one since I already got started on it.

**Comment by AraOshin** [comment]
@hassanshamim when do you think is a feasible timeline for completing this list?

**Comment by hassanshamim** [comment]
@AraOshin working on these now!  Hoping to have all of these done by end of the day.

**Comment by AraOshin** [comment]
@hassanshamim amazing! Already seeing ims_neighborhood_demographics which looks great!

**Comment by hassanshamim** [comment]
`campsite_reports_by_month_neigh` is the new materialized view for the requested reports aggregation.  I *believe* that Katy is still putting some final touches on campsite reports, so I'll be updating the original reports and refreshing this view, so some of the final counts may change.

**Comment by AraOshin** [comment]
@hassanshamim  I have to run so excuse my brevity here. Can help fill in more detail later on if needed : 
three new sandbox db requests: 

1. bus stops, mp to point 
2. trees aggregation table columns: id, neighborhood_name, year, count(of trees in that neighborhood, for that year) 
3. can you convert the handful (8 I think) parkstrails features that are in fact multilinestrings into linstrings using postgres? django's merged is not working well for me so if this could be fixed on the db end that would make my life easier... this is lowest priority. No worries if you don't get to it.

**Comment by hassanshamim** [comment]
- [ ] bus stops, mp to point
- [ ] trees aggregation table columns: id, neighborhood_name, year, count(of trees in that neighborhood, for that year)
- [ ] can you convert the handful (8 I think) parkstrails features that are in fact multilinestrings into linstrings using postgres? django's merged is not working well for me so if this could be fixed on the db end that would make my life easier... this is lowest priority. No worries if you don't get to it.

**Comment by hassanshamim** [comment]
Closing this for my sanity.  Please make new issues for the taxlot/parktrails if you need them.
