### ISSUE TITLE
Campsite Reports & Sweeps bar chart - Add filter for vehicles

### ISSUE THREAD

**Issue by mckinneybock** [hackoregon/neighborhoods-2018#63]
For the card/API endpoint that contains both campsite reports and sweeps, aggregated by time (month) as a line plot, we need to add a filter to the endpoint that takes the field "Is this a vehicle?" and only pulls the ones that are FALSE (i.e. not vehicles).

**Comment by hassanshamim** [comment]
TODO
- [ ] campsite reports aggregated by month (with vehicles=True removed)
- [ ] campsite sweeps aggregated by month
-  [ ] *unique* campsites by month

**Comment by hassanshamim** [comment]
table `campsites_unique_sites_by_week` for unique campsites by week

**Comment by hassanshamim** [comment]
for hackoregon/civic#100

**Comment by hassanshamim** [comment]
closed by #83
