### ISSUE TITLE
Dataset QA Workflow - Sweeps (camp_cleanups) 

### ISSUE THREAD

**Issue by AraOshin** [hackoregon/neighborhoods-2018#7]
We need to move datasets through a QA workflow before uploading the (hopefully) finalized version to our AWS database.

QA tasks:

- [ ]     1. check for geocode errors (related to scope)

Use the below SQL syntax to filter the dataset to return only rows where the current geocoded location is not returning as inside our team’s scope (Portland metro): (replace <table_name> with dataset table name)

select 
<tabel_name>.*
from <table_name>
where <table_name>.id not in 
(select <table_name>.id
from <table_name>
join scope on ST_Contains (scope.geom, <table_name>.geom))

If the returned points are in fact not in Portland Metro, then everything is fine. However, if the point describes a location that is in the Portland metro, there is an error somewhere, probably in the geocoded location. Update the dataset to fix errors (document this process).

- [ ]     2. finalize dataset field names

    Make sure spelling is correct and none are cut off.

    Are the names logical? Could they be improved so that front end devs and anyone else in the future could more easily understand?

    If changing field names: use lowercase, underscores, start all field names with a letter and no other symbols (such as + , .  - and no spaces!).

- [ ]     3. address missing data

    any columns missing data completely? Address issue or remove column from dataset if there is no data for that field

    Check on null values, zeros, and blanks. Make sure decisions regarding missing data is documented and handled according to team processes.

- [ ] 4. Run other queries/procedures to aggregate and asses data to ensure dataset fidelity (especially regarding geocoding).

Once this is all done, mark issue as complete and send the updated dataset file to Zachary and Lynn. The database will then be updated.

**Comment by AraOshin** [comment]
Also, @mckinneybock I believe we have agreed to rename this dataset to campsite_sweeps (or could be just sweeps but since we will have a campsite reports set it probably makes sense to keep the descriptor?) The dataset will be renamed during the database update after this issue is complete.

**Comment by mckinneybock** [comment]
Here is what I'm working on this week:

- Coding April-May sweeps data (adding new data)
- Fixing the 25 data points that were mis-coded
- General Spot-checking of dataset for matching geocodes to intersections to confirm integrity of the data.

**Comment by LMorgan-veraly** [comment]
Sweeps are now in AWS DB, see storycards in progress.
