### ISSUE TITLE
Correct primary.field meta attribute

### ISSUE THREAD

**Issue by nam20485** [hackoregon/neighborhoods-2018#94]
slide_meta.attributes.primary.field should be “description”

**Comment by nam20485** [comment]
@mendozaline, @LMorgan-veraly 

I set `demolitions_meta.primary.field` to 'description' but a value for `demolitions_meta.primary.name` isn't specified. I used 'Demolitions Data from 2000 to 2018' for now. Is there something better that I could use?

**Comment by mendozaline** [comment]
You can use "Demolition Description" for the name.
